# services:
#   app:
#     build: .
#     container_name: sumai-app
#     volumes:
#       - .:/var/www/html
#     ports:
#       - "8000:80"
#     depends_on:
#       - queue
#     command: >
#       sh -c "php artisan migrate && php artisan serve --host=0.0.0.0 --port=80"
#     environment:
#       - DB_CONNECTION=sqlite
#       - DB_DATABASE=/var/www/html/database/database.sqlite

#   queue:
#     build: .
#     container_name: sumai-queue
#     volumes:
#       - .:/var/www/html
#     command: >
#       sh -c "
#         composer install &&
#         php artisan storage:link &&
#         php artisan migrate &&
#         php artisan queue:work
#       "
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - ./summarizer:/var/www/html
      - ./.env:/var/www/html/.env
    depends_on:
      - mysql
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=Alvino098101.
    command: sh /usr/local/bin/start.sh
    networks:
      - laravel

  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - ./summarizer:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: password123
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:



